- project:
    templates:
      - openstack-python-jobs-neutron
      - openstack-python35-jobs-neutron
      - release-notes-jobs-python3
      - publish-openstack-docs-pti
      - check-requirements
    check:
      jobs:
        - networking-baremetal-dsvm-multitenant-vlans
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - networking-baremetal-dsvm-multitenant-vlans
        - openstack-tox-lower-constraints
