- project:
    templates:
        - openstack-python-jobs
        - openstack-python35-jobs
        - release-notes-jobs-python3
        - publish-openstack-docs-pti
    check:
      jobs:
        - networking-baremetal-dsvm-multitenant-vlans
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - networking-baremetal-dsvm-multitenant-vlans
        - openstack-tox-lower-constraints
